### PR TITLE
Feature/sfdc lead update phase2

### PR DESCRIPTION
**Pull request by RiteshTC**
@vikasrohit 
I have done the change related to creating /  updating Lead Fields in SFDC when
1) Connect Project Status Changes
2) Ref Code is created / updated
3) Cancel Reason when Project is Cancelled

https://docs.google.com/document/d/1QarSiMrkoAMXqb7trL9dP-iWfIp-nA1OLEzchlD-gbE/edit

### CODE REVIEW

**Comment by fnisen** [comment]
Thanks @vikasrohit. I remember I got confused by the various environments last time. How do I access Salesforce in dev please?

**Comment by vikasrohit** [comment]
You can go to test.salesforce.com and enter your sandbox credentials there. If you are unable to locate your salesforce sandbox credentials, @riteshTC can help you here.

**Comment by RiteshTC** [comment]
@fnisen
Your dev sandbox username is "fnisenzoun1@topcoder.com.dev" and you can login to https://test.salesforce.com.

**Comment by fnisen** [comment]
@RiteshTC I'm having trouble resetting my password there. Get this message: "You haven't selected an answer to your password hint." Can you please help?

Also, are there only two environments now: dev sandbox and production?

**Comment by RiteshTC** [comment]
@fnisen 
I have reset your password. You will be receiving an email from SFDC to reset the password.

We have actually 3 environments.
1) Production (Username : (fnisenzoun@topcoder.com) 
2) Dev Sandbox  ( 	fnisenzoun1@topcoder.com.dev )
3) Full Sandbox (  fnisenzoun1@topcoder.com.full)

Dev is mostly used for development related work, and doesn't contain any real data.
Full sandbox used for migration, and other load testing. It contains a replica of production data, with real names and emails.

**Comment by fnisen** [comment]
Thanks @RiteshTC. So, do you deploy from Dev to Full (and then to Prod) or from Dev to Prod right away?

**Comment by RiteshTC** [comment]
@fnisen 
For new functionality ( that doesn't change or modify any existing data ), we deploy directly from dev to prod. 
For any issues or bugs related to existing functionality (that may impact existing data), the preferred way is to have a go from "dev" to "full" to "prod".

**Comment by RiteshTC** [comment]
@fnisen 
Did you get a chance to review the task ?

**Comment by fnisen** [comment]
@RiteshTC sorry for the delay. I've reviewed and it looks good. Please deploy. Thank you!

I only noticed one issue: the project link in SFDC is not environment specific (meaning the link in SFDC dev actually goes to Connect prod, not Connect dev). This is not a big deal b/c the link does work.

**Comment by RiteshTC** [comment]
@fnisen 
Thanks for reviewing. We will be deploying the changes later today.
Oh ! yes the connect link is set to prod for all SFDC environment(s). I will change it to use connect dev in sandboxes, to prevent confusion.

**Comment by RiteshTC** [comment]
@fnisen 
The changes have been deployed. Thanks to @vikasrohit for the help.
[Release Notes](https://github.com/appirio-tech/tc-connect2sf/releases/tag/1.2.0)

**Comment by fnisen** [comment]
Very nice, thank you guys. 🎉

**Pull request merged**
